
#pragma once

// #undef DISABLE_RGB_MATRIX_GRADIENT_UP_DOWN
// #undef DISABLE_RGB_MATRIX_BAND_SAT
// #undef DISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
// #undef DISABLE_RGB_MATRIX_BAND_SPIRAL_SAT
// #undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
// #undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
// #undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
// #undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
// #undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
// #undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
// #undef DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
// #undef DISABLE_RGB_MATRIX_SPLASH
// #undef DISABLE_RGB_MATRIX_MULTISPLASH
// #undef DISABLE_RGB_MATRIX_SOLID_SPLASH
// #undef DISABLE_RGB_MATRIX_SOLID_MULTISPLASH
// #undef DISABLE_RGB_MATRIX_DIGITAL_RAIN
// #undef DISABLE_RGB_MATRIX_RAINDROPS
// #undef DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPs
#undef RGB_MATRIX_STARTUP_MODE

#define DISABLE_RGB_MATRIX_DUAL_BEACON
#define DISABLE_RGB_MATRIX_BAND_SAT
#define DISABLE_RGB_MATRIX_BAND_VAL
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_NONE
